// packages/kuat-vue/src/components/ui/checkbox/Checkbox.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { computed, useAttrs } from "vue"
import { CheckboxIndicator, CheckboxRoot } from "reka-ui"
import { Check, Minus } from "lucide-vue-next"
import { cn } from "@/lib/utils"
import "./checkbox.css"

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()

const model = defineModel<boolean | "indeterminate">({ required: false })

const attrs = useAttrs()

const delegatedAttrs = computed(() => {
  const { class: _c, ...rest } = attrs as Record<string, unknown>
  return rest
})
</script>

<template>
  <CheckboxRoot
    v-model="model"
    data-slot="checkbox"
    :class="cn('checkbox', props.class)"
    v-bind="delegatedAttrs"
  >
    <CheckboxIndicator class="checkbox__indicator">
      <Check class="checkbox__icon checkbox__icon--check" aria-hidden="true" />
      <Minus class="checkbox__icon checkbox__icon--indeterminate" aria-hidden="true" />
    </CheckboxIndicator>
  </CheckboxRoot>
</template>

// packages/kuat-react/src/components/ui/checkbox/checkbox.tsx
"use client"

import * as React from "react"
import * as CheckboxPrimitive from "@radix-ui/react-checkbox"
import { Check, Minus } from "lucide-react"

import { cn } from "@/lib/utils"

import "./checkbox.css"

const Checkbox = React.forwardRef<
  React.ElementRef<typeof CheckboxPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root>
>(({ className, ...props }, ref) => (
  <CheckboxPrimitive.Root
    ref={ref}
    className={cn("checkbox", className)}
    data-slot="checkbox"
    {...props}
  >
    <CheckboxPrimitive.Indicator className="checkbox__indicator">
      <Check className="checkbox__icon checkbox__icon--check" aria-hidden />
      <Minus className="checkbox__icon checkbox__icon--indeterminate" aria-hidden />
    </CheckboxPrimitive.Indicator>
  </CheckboxPrimitive.Root>
))
Checkbox.displayName = CheckboxPrimitive.Root.displayName

export type CheckboxProps = React.ComponentPropsWithoutRef<typeof Checkbox>

export { Checkbox }
