// packages/kuat-react/src/components/ui/input/input.tsx
"use client"

import * as React from "react"

import { cn } from "@/lib/utils"

import "./input.css"

export const INPUT_SIZES = ["regular", "large", "small", "mini"] as const
export type InputSize = (typeof INPUT_SIZES)[number]

export interface InputProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "size"> {
  /** Visual size; maps to `input--size-*` (not the HTML `size` attribute). */
  size?: InputSize
  /** Optional content before the field (icon, text, checkbox, etc.). */
  leftDecoration?: React.ReactNode
  /** Optional content after the field (suffix text, button, icon, etc.). */
  rightDecoration?: React.ReactNode
}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  (
    {
      className,
      size = "regular",
      leftDecoration,
      rightDecoration,
      type = "text",
      ...props
    },
    ref
  ) => {
    return (
      <div
        className={cn("input", `input--size-${size}`, className)}
        data-slot="input"
      >
        {leftDecoration ? (
          <span className="input__decoration input__decoration--left">
            {leftDecoration}
          </span>
        ) : null}
        <input
          ref={ref}
          type={type}
          className="input__field"
          data-slot="input-field"
          {...props}
        />
        {rightDecoration ? (
          <span className="input__decoration input__decoration--right">
            {rightDecoration}
          </span>
        ) : null}
      </div>
    )
  }
)
Input.displayName = "Input"

export { Input }

// packages/kuat-vue/src/components/ui/input/Input.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { computed, useAttrs } from "vue"
import { cn } from "@/lib/utils"
import type { InputSize } from "./constants"
import "./input.css"

defineOptions({ inheritAttrs: false })

const props = withDefaults(
  defineProps<{
    class?: HTMLAttributes["class"]
    size?: InputSize
  }>(),
  { size: "regular" }
)

const model = defineModel<string>({ required: false })
const attrs = useAttrs()

const delegatedAttrs = computed(() => {
  const { class: _c, ...rest } = attrs as Record<string, unknown>
  return rest
})

/** `type="file"` must not use string v-model; consumers use @change / ref. */
const isFileInput = computed(() => delegatedAttrs.value.type === "file")
</script>

<template>
  <div
    data-slot="input"
    :class="
      cn(
        'input',
        `input--size-${props.size}`,
        isFileInput && 'input--type-file',
        props.class
      )
    "
  >
    <span
      v-if="$slots.leftDecoration"
      class="input__decoration input__decoration--left"
    >
      <slot name="leftDecoration" />
    </span>
    <input
      v-if="!isFileInput"
      data-slot="input-field"
      class="input__field"
      v-bind="delegatedAttrs"
      v-model="model"
    />
    <input
      v-else
      data-slot="input-field"
      class="input__field"
      v-bind="delegatedAttrs"
    />
    <span
      v-if="$slots.rightDecoration"
      class="input__decoration input__decoration--right"
    >
      <slot name="rightDecoration" />
    </span>
  </div>
</template>
