// packages/kuat-react/src/components/ui/toggle/toggle.tsx
"use client"

import * as React from "react"
import * as TogglePrimitive from "@radix-ui/react-toggle"

import { cn } from "@/lib/utils"

import { type ToggleSize, type ToggleSkin } from "./constants"
import "./toggle.css"

export interface ToggleProps
  extends React.ComponentPropsWithoutRef<typeof TogglePrimitive.Root> {
  size?: ToggleSize
  skin?: ToggleSkin
}

const Toggle = React.forwardRef<
  React.ElementRef<typeof TogglePrimitive.Root>,
  ToggleProps
>(({ className, size = "regular", skin = "outlined", ...props }, ref) => (
  <TogglePrimitive.Root
    ref={ref}
    className={cn("toggle", `toggle--size-${size}`, `toggle--skin-${skin}`, className)}
    data-slot="toggle"
    {...props}
  />
))
Toggle.displayName = TogglePrimitive.Root.displayName

export { Toggle }

// packages/kuat-vue/src/components/ui/toggle/Toggle.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import type { ToggleSize, ToggleSkin } from "./constants"
import { computed, useAttrs } from "vue"
import { Toggle as RekaToggle } from "reka-ui"
import { cn } from "@/lib/utils"
import "./toggle.css"

defineOptions({ inheritAttrs: false })

const props = withDefaults(
  defineProps<{
    class?: HTMLAttributes["class"]
    size?: ToggleSize
    skin?: ToggleSkin
  }>(),
  {
    size: "regular",
    skin: "outlined",
  }
)

const model = defineModel<boolean>({ required: false })
const attrs = useAttrs()

const delegatedAttrs = computed(() => {
  const { class: _c, ...rest } = attrs as Record<string, unknown>
  return rest
})
</script>

<template>
  <RekaToggle
    v-model="model"
    data-slot="toggle"
    v-bind="delegatedAttrs"
    :class="cn('toggle', `toggle--size-${props.size}`, `toggle--skin-${props.skin}`, props.class)"
  >
    <slot />
  </RekaToggle>
</template>
