// packages/kuat-vue/src/components/ui/content-card/ContentCard.vue
<script setup lang="ts">
import type { CSSProperties, HTMLAttributes } from "vue"
import { computed } from "vue"
import type { PrimitiveProps } from "reka-ui"
import { Primitive } from "reka-ui"

import { cn } from "@/lib/utils"


interface Props extends PrimitiveProps {
  class?: HTMLAttributes["class"]
  /** Width behavior for the root card container. */
  width?: "default" | "fluid" | "custom"
  /** Used when `width` is `custom`; accepts CSS max-width values. */
  maxWidth?: string | number
  /** Optional media; when `null`, the media area is removed (no gap). */
  imageSrc?: string | null
  imageAlt?: string

  /** Header props (not slots). */
  category: string
  title: string
  titleHeadingLevel: 1 | 2 | 3 | 4 | 5 | 6

  /** Optional basic content text (hidden when omitted). */
  contentText?: string | null
}

const props = withDefaults(defineProps<Props>(), {
  as: "div",
  width: "default",
  maxWidth: "373px",
  imageSrc: null,
  imageAlt: "",
  contentText: null,
})

const headingTag = computed(() => `h${props.titleHeadingLevel}`)
const widthClass = computed(() => {
  if (props.width === "fluid") return "content-card--width-fluid"
  if (props.width === "custom") return "content-card--width-custom"
  return "content-card--width-default"
})
const rootStyle = computed<CSSProperties | undefined>(() => {
  if (props.width !== "custom") return undefined
  const value = typeof props.maxWidth === "number" ? `${props.maxWidth}px` : props.maxWidth
  return { "--content-card-max-width": value } as CSSProperties
})
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="cn('content-card', widthClass, props.class)"
    :style="rootStyle"
    data-slot="content-card"
    v-bind="$attrs"
  >
    <slot v-if="asChild" />
    <div v-if="props.imageSrc !== null" class="content-card__media">
      <img class="content-card__media-img" :src="props.imageSrc" :alt="props.imageAlt" />
    </div>

    <div class="content-card__body">
      <div class="content-card__heading-row">
        <div class="content-card__heading-left">
          <div class="content-card__heading-meta">
            <div data-slot="badge" class="content-card__badge">
              <slot name="badge" />
            </div>
            <p class="content-card__category">{{ props.category }}</p>
          </div>

          <component :is="headingTag" class="content-card__title">
          {{ props.title }}
          </component>
        </div>

        <div data-slot="header-accessory" class="content-card__header-accessory">
          <slot name="header-accessory" />
        </div>
      </div>

      <div v-if="props.contentText != null" data-slot="content" class="content-card__content">
        <p class="content-card__content-text">{{ props.contentText }}</p>
      </div>

      <div data-slot="custom-content" class="content-card__custom-content">
        <slot name="custom-content" />
      </div>

      <div data-slot="footer" class="content-card__footer">
        <slot name="footer" />
      </div>
    </div>
  </Primitive>
</template>

<style scoped>
@reference "../../../styles.css";

.content-card {
  @apply flex flex-col items-start relative border border-border bg-card pb-2 w-full border-solid min-w-0;
}

.content-card--width-default {
  @apply max-w-[373px];
}

.content-card--width-fluid {
  @apply max-w-none;
}

.content-card--width-custom {
  max-width: var(--content-card-max-width, 373px);
}

.content-card__media {
  @apply relative shrink-0 h-[192px] w-full;
}

.content-card__media-img {
  @apply inset-0 max-w-none object-cover pointer-events-none size-full;
}

.content-card__body {
  @apply flex flex-col gap-4 items-start p-4 relative shrink-0 w-full;
}

.content-card__heading-row {
  @apply flex items-start justify-between overflow-clip shrink-0 w-full;
}

.content-card__heading-left {
  @apply flex flex-[1_0_0] flex-col gap-1 items-start min-h-px min-w-px relative;
}

.content-card__header-accessory {
  @apply flex flex-col items-start justify-start overflow-clip gap-2 shrink-0 ;
}

.content-card__badge {
  @apply flex items-center;
}

.content-card__heading-meta {
  @apply flex gap-2 items-center shrink-0 w-full;
}

.content-card__category {
  @apply whitespace-nowrap text-xs font-medium text-ee-blue-700;
}

.content-card__title {
  @apply w-full max-w-[250px] text-2xl font-semibold tracking-tight text-foreground ;
}

.content-card__content {
  @apply overflow-clip relative shrink-0 w-full;
}

.content-card__content-text {
  @apply text-foreground whitespace-pre-wrap;
}

.content-card__custom-content {
  @apply overflow-clip relative shrink-0 w-full;
}

.content-card__footer {
  @apply overflow-clip relative shrink-0 w-full;
}
</style>

// packages/kuat-react/src/components/ui/content-card/content-card.tsx
"use client"

import * as React from "react"

import { cn } from "@/lib/utils"
import type { KuatSlotContent } from "@/lib/react-node-compat"
import "./content-card.css"

export interface ContentCardProps
  extends Omit<
    React.HTMLAttributes<HTMLDivElement>,
    "content" | "children" | "title"
  > {
  className?: string
  asChild?: boolean
  /** Optional media; when `null`, the media area is removed (no gap). */
  imageSrc?: string | null
  imageAlt?: string

  /** Header props (not slots). */
  badge: KuatSlotContent
  category: KuatSlotContent
  title: KuatSlotContent
  titleHeadingLevel: 1 | 2 | 3 | 4 | 5 | 6

  /** Optional basic content text (hidden when omitted). */
  contentText?: string | null

  /** Header Accessory slot (flex row). */
  headerAccessory?: KuatSlotContent | null

  /** Custom content slot below basic content. */
  customContent?: KuatSlotContent | null

  /** Footer slot. */
  footer?: KuatSlotContent | null

  children?: KuatSlotContent
  /** Width behavior for the root card container. */
  width?: "default" | "fluid" | "custom"
  /** Used when `width` is `custom`; accepts CSS max-width values. */
  maxWidth?: React.CSSProperties["maxWidth"]
}

const ContentCard = React.forwardRef<HTMLDivElement, ContentCardProps>(function ContentCard(
  {
    className,
    asChild = false,
    width = "default",
    maxWidth = "373px",
    imageSrc = null,
    imageAlt = "",
    contentText = null,
    headerAccessory = null,
    customContent = null,
    footer = null,
    badge,
    category,
    title,
    titleHeadingLevel = 3,
    children,
    style,
    ...props
  },
  ref
) {
  const HeadingTag = (`h${titleHeadingLevel}` as unknown) as keyof JSX.IntrinsicElements
  const widthClassName =
    width === "fluid"
      ? "content-card--width-fluid"
      : width === "custom"
        ? "content-card--width-custom"
        : "content-card--width-default"
  const resolvedStyle =
    width === "custom"
      ? ({
          ...((style as React.CSSProperties | undefined) ?? {}),
          "--content-card-max-width":
            typeof maxWidth === "number" ? `${maxWidth}px` : (maxWidth ?? "373px"),
        } as React.CSSProperties)
      : style

  const internalMarkup = (
    <>
      {imageSrc !== null ? (
        <div className="content-card__media">
          <img className="content-card__media-img" alt={imageAlt} src={imageSrc} />
        </div>
      ) : null}

      <div className="content-card__body">
        <div className="content-card__heading-row">
          <div className="content-card__heading-left">
            <div className="content-card__heading-meta">
              <div data-slot="badge" className="content-card__badge">
                {badge}
              </div>
              <p className="content-card__category">{category}</p>
            </div>
            <HeadingTag className="content-card__title">{title}</HeadingTag>
          </div>

          <div
            data-slot="header-accessory"
            className="content-card__header-accessory"
          >
            {headerAccessory ?? null}
          </div>
        </div>

        {contentText != null ? (
          <div data-slot="content" className="content-card__content">
            <p className="content-card__content-text">{contentText}</p>
          </div>
        ) : null}

        <div data-slot="custom-content" className="content-card__custom-content">
          {customContent ?? null}
        </div>

        <div data-slot="footer" className="content-card__footer">
          {footer ?? null}
        </div>
      </div>
    </>
  )

  if (asChild) {
    const onlyChild = React.Children.only(children)
    if (!React.isValidElement(onlyChild)) {
      throw new Error("ContentCard: when `asChild` is true, provide a single React element child.")
    }

    const onlyChildElement = onlyChild as React.ReactElement<{
      className?: string
      style?: React.CSSProperties
      [key: string]: unknown
    }>

    return React.cloneElement(
      onlyChildElement,
      {
        ...(props as unknown as Record<string, unknown>),
        ref,
        "data-slot": "content-card",
        className: cn("content-card", widthClassName, onlyChildElement.props.className, className),
        style:
          width === "custom"
            ? {
                ...(onlyChildElement.props.style ?? {}),
                ...(resolvedStyle as React.CSSProperties),
              }
            : (resolvedStyle ?? onlyChildElement.props.style),
      } as unknown as Record<string, unknown>,
      internalMarkup
    )
  }

  return (
    <div
      ref={ref}
      data-slot="content-card"
      className={cn("content-card", widthClassName, className)}
      style={resolvedStyle}
      {...props}
    >
      {internalMarkup}
    </div>
  )
})

export { ContentCard }
