// packages/kuat-react/src/components/ui/switch/switch-field.tsx
"use client"

import * as React from "react"

import { cn } from "@/lib/utils"

import {
  Field,
  FieldContent,
  FieldDescription,
  FieldLabel,
  FieldTitle,
} from "../field"
import { Switch } from "./switch"

import "./switch-field.css"

export const SWITCH_FIELD_APPEARANCES = ["plain", "card"] as const
export type SwitchFieldAppearance = (typeof SWITCH_FIELD_APPEARANCES)[number]

export const SWITCH_FIELD_LAYOUTS = ["inline", "block"] as const
export type SwitchFieldLayout = (typeof SWITCH_FIELD_LAYOUTS)[number]

/** @deprecated Prefer composing `Field` + `Switch` for new form layouts. */
export interface SwitchFieldProps
  extends Omit<React.ComponentPropsWithoutRef<typeof Switch>, "id" | "children"> {
  /** Primary label (always shown). */
  label: React.ReactNode
  /** Optional secondary line (12px muted); works for both plain and card. */
  secondaryText?: React.ReactNode
  /** `plain` — no border/padding; `card` — bordered padded container. */
  appearance?: SwitchFieldAppearance
  /** `inline` — compact label; `block` — label row can grow. */
  layout?: SwitchFieldLayout
  /** Place switch on the right of the text block. */
  flipped?: boolean
  id?: string
}

/** @deprecated Prefer composing `Field` + `Switch` for new form layouts. */
const SwitchField = React.forwardRef<
  React.ElementRef<typeof Switch>,
  SwitchFieldProps
>(
  (
    {
      className,
      label,
      secondaryText,
      appearance = "plain",
      layout = "inline",
      flipped = false,
      id: idProp,
      disabled,
      ...switchProps
    },
    ref
  ) => {
    const generatedId = React.useId()
    const id = idProp ?? generatedId
    const hasSecondary = secondaryText != null
    const isInvalid =
      switchProps["aria-invalid"] === true ||
      switchProps["aria-invalid"] === "true"

    return (
      <Field
        className={cn(
          "switch-field",
          `switch-field--appearance-${appearance}`,
          `switch-field--layout-${layout}`,
          hasSecondary && "switch-field--has-secondary",
          flipped && "switch-field--flipped",
          disabled && "switch-field--disabled",
          isInvalid && "switch-field--invalid",
          className
        )}
        data-slot="switch-field"
      >
        <FieldLabel className="switch-field__label" htmlFor={id}>
          <span className="switch-field__switch-wrap">
            <Switch ref={ref} id={id} disabled={disabled} {...switchProps} />
          </span>
          <FieldContent className="switch-field__text">
            <FieldTitle className="switch-field__primary">{label}</FieldTitle>
            {hasSecondary ? (
              <FieldDescription className="switch-field__secondary">
                {secondaryText}
              </FieldDescription>
            ) : null}
          </FieldContent>
        </FieldLabel>
      </Field>
    )
  }
)
SwitchField.displayName = "SwitchField"

export { SwitchField }

// packages/kuat-vue/src/components/ui/switch/SwitchField.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { computed, useAttrs, useId } from "vue"
import { reactiveOmit } from "@vueuse/core"
import { cn } from "@/lib/utils"
import {
  Field,
  FieldContent,
  FieldDescription,
  FieldLabel,
  FieldTitle,
} from "../field"
import Switch from "./Switch.vue"
import type { SwitchFieldAppearance, SwitchFieldLayout } from "./constants"
import "./switch-field.css"

defineOptions({ inheritAttrs: false })

const props = withDefaults(
  defineProps<{
    class?: HTMLAttributes["class"]
    /** @deprecated Prefer composing `Field` + `Switch` for new form layouts. */
    label: string
    secondaryText?: string
    appearance?: SwitchFieldAppearance
    layout?: SwitchFieldLayout
    flipped?: boolean
    id?: string
    disabled?: boolean
  }>(),
  {
    appearance: "plain",
    layout: "inline",
    flipped: false,
  }
)

const model = defineModel<boolean>({ required: false })

const attrs = useAttrs()

const generatedId = useId()
const fieldId = computed(() => props.id ?? generatedId)

const hasSecondary = computed(() => props.secondaryText != null)

const switchProps = reactiveOmit(props, [
  "label",
  "secondaryText",
  "appearance",
  "layout",
  "flipped",
  "id",
  "class",
  "disabled",
])

/** Field props for the inner Switch plus fallthrough attrs (e.g. aria-invalid). */
const switchBind = computed(() => {
  const { class: _c, ...fromAttrs } = attrs as Record<string, unknown>
  return { ...switchProps, ...fromAttrs }
})

const isInvalid = computed(() => {
  const v = (switchBind.value as Record<string, unknown>)["aria-invalid"]
  return v === true || v === "true"
})
</script>

<template>
  <Field
    data-slot="switch-field"
    :class="
      cn(
        'switch-field',
        `switch-field--appearance-${appearance}`,
        `switch-field--layout-${layout}`,
        hasSecondary && 'switch-field--has-secondary',
        flipped && 'switch-field--flipped',
        disabled && 'switch-field--disabled',
        isInvalid && 'switch-field--invalid',
        props.class
      )
    "
  >
    <FieldLabel class="switch-field__label" :for="fieldId">
      <span class="switch-field__switch-wrap">
        <Switch
          :id="fieldId"
          v-model="model"
          v-bind="switchBind"
          :disabled="disabled"
        />
      </span>
      <FieldContent class="switch-field__text">
        <FieldTitle class="switch-field__primary">{{ label }}</FieldTitle>
        <FieldDescription v-if="hasSecondary" class="switch-field__secondary">
          {{ secondaryText }}
        </FieldDescription>
      </FieldContent>
    </FieldLabel>
  </Field>
</template>
